---
title: "Research and Teaching"
---

I am interested in studying how meso and submesoscale vortices affect the development of planktonic communities and how oceanic variability influences extreme weather events on the continent. Additionally, I investigate the interaction between physical processes, such as how vortices can group internal waves that break and generate mixing in the interior ocean. I use cutting-edge computational tools to analyze and visualize observational and model data, as well as to develop new methods and tools for data analysis and visualization.

I am also passionate about educational and diversity projects. As a scientist, I believe in making my research accessible to a broader audience and promoting diversity in STEM. To this end, I am committed to developing outstanding courses that find creative ways to teach computational oceanography in underprivileged universities and communities. I believe everyone should have the opportunity to learn about the exciting world of oceanography and its vital role in understanding our planet.

Through my research and educational efforts, I aim to contribute to a better understanding of our planet's complex systems and to inspire the next generation of scientists and leaders. In addition, I am committed to collaborating with fellow researchers and sharing my knowledge and expertise with students and the wider community.

# Publications


<br>

<script src="https://bibbase.org/show?bib=https://iuryt.github.io/pubs.bib&jsonp=1&theme=dividers"></script>