---
title: "Cookbook for nice scientific presentations"
author: "Iury Simoes-Sousa"
date: "2023-04-10"
categories: [[Science]]
toc: true
toc-location: left
fig-align: center
---

This post is a **work in progress** and will be updated every time I remember something new or have new good tips to add.
The idea is to make a cookbook with examples and counter-examples for preparing **good scientific presentations**, but for now I will simply list what I personally consider good practices for preparing a good presentation. This is a compilation of my own opinions, tips that I have received from various people and sources that I have not yet organized in a systematic way, i.e. it is not restricted to my own ideas, but ideas that I have also collected throughout my still short academic career.

- On the **first slide** you must make clear the **topic of the presentation, authors, funding agencies, and affiliated institutions**. The funding agencies can also be on the acknowledgements slide. You can also add a summary image that gives a graphic idea of the object of study, but it is not essential.
- Prefer a **white background**, but you can use **color design for sidebars, top or bottom**.
- **Always number your slides.** This is extremely important to help people elaborate and reference the questions at the end of the presentation.
- Use a **color code for different context**. For example, standard text can be in black with some bold. Important things in red and quotes in green. This can help people identify the main points without having to read the whole text.
- After the title slide you can have a short slide to **introduce yourself**. This is especially important for early-career scientists. You can list your projects, collaborations, scientific interests, and even comment on some hobbies that you have. This is a good opportunity to **connect with the audience**, so you can mention something that connects you to the place you are presenting or to people in the audience.
- After that you can have an **outline slide**, which gives a general idea of the path you will take with the audience. While not mandatory, it can help the audience understand the order and logic of the presentation, but don't go into too much detail. It is just to give an idea.
- I like to start the presentation itself with a slide that has **minimal text** and an image that takes up much of the space. This **image should impact the audience** and give a visual sense of the object of study. For example, I often present my work on phytoplankton blooms by presenting an image of trees in springtime bloom on the mainland. Soon afterwards I present a satellite image of phytoplankton blooms in the open ocean. This usually has an impact and makes it clear up front that the main topic of the paper is spring blooms and that, despite the differences, they also occur in the ocean.
- I usually always **explicitly present the scientific questions** and the central goal of the introduction is to try as much as possible to **make the audience almost predict these questions**, i.e. to make clear what has not yet been investigated and its importance.
- For content slides, I generally **start building the slide with an image** and add text only for what the image does not say by itself, or for things that I want to emphasize in the image. This prevents the slides from having too much text.
- Please **explicitly explain what is being presented in the figures**, their axes, colors, units, etc..
- Towards the end of each section, you can **remind the audience what we learned** from those analyses. Not everything will seem obvious to those watching, so it's important to make that explicit.
- **Prepare a good question or statement for the last slide.** Avoid ending with an explicit thank you. The idea is to make the audience want to learn more about the subject, so try to stimulate their curiosity with a last message.

I wrote this post in just a few minutes and with all certainty I know I am leaving out most of the complexity surrounding this topic. Over time I plan to populate and update this post with new ideas, but if you have any other ideas that you don't see covered here, you can also post them in the comments here below.